import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'vi' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.tables": "Tables",
    "nav.menu": "Menu",
    "nav.history": "Order History",
    "nav.inventory": "Inventory",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    "nav.logout": "Sign Out",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your preferences and system configuration",
    "settings.general": "General",
    "settings.appearance": "Appearance",
    "settings.appearance_desc": "Customize how EcoPOS looks on your device",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.language": "Language",
    "settings.language_desc": "Select your preferred interface language",
    "settings.currency": "Currency",
    "settings.currency_desc": "Default currency for pricing",
    "settings.business": "Business",
    "settings.tax": "Tax Rate (%)",
    "settings.tax_desc": "Applied to all eligible orders",
    "settings.save": "Save",
    "settings.notifications": "Notifications",
    "settings.order_alerts": "Order Alerts",
    "settings.order_alerts_desc": "Get notified when a new order is placed",
    "settings.stock_alerts": "Low Stock Warning",
    "settings.stock_alerts_desc": "Alert when inventory drops below threshold",
    "settings.about": "About",
    "settings.edit_profile": "Edit Profile",
    "settings.avatar_url": "Avatar URL",
    "settings.avatar_hint": "Click image to upload",
    "settings.randomize": "Randomize",
    "settings.security": "Security",
    "settings.change_password": "Change Password",
    "settings.change_password_desc": "Update your account password",
    "settings.current_password": "Current Password",
    "settings.new_password": "New Password",
    "settings.confirm_password": "Confirm Password",
    "settings.password_match_error": "Passwords do not match",
    "settings.password_old_error": "Incorrect current password",
    "settings.password_updated": "Password updated successfully",
    "role.admin": "Admin",
    "role.manager": "Manager",
    "role.cashier": "Cashier",

    // Login
    "login.welcome": "Welcome Back",
    "login.subtitle": "Please enter your details to sign in.",
    "login.create_account": "Create Account",
    "login.create_subtitle": "Join EcoPOS as a new cashier.",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.fullname": "Full Name",
    "login.signin": "Sign In",
    "login.signup": "Sign Up",
    "login.already_have_account": "Already have an account?",
    "login.dont_have_account": "Don't have an account?",
    "login.brand_subtitle": "The smart, sustainable solution for modern restaurant management.",
    "login.feature_floor": "Real-time Floor Plan",
    "login.feature_inventory": "Smart Inventory",
    "login.feature_analytics": "AI Analytics",

    // Tables
    "tables.title": "Floor Plan",
    "tables.live_view": "Live View",
    "tables.editing": "Editing Layout...",
    "tables.add_table": "Add Table",
    "tables.edit_layout": "Edit Layout",
    "tables.done": "Done",
    "tables.all_areas": "All Areas",
    "tables.status_open": "Open",
    "tables.status_occupied": "Occupied",
    "tables.status_dirty": "Dirty",
    "tables.seats": "Seats",
    "tables.guests": "Guests",
    "tables.time": "Time",
    "tables.current_order": "Current Order",
    "tables.action_order": "Order",
    "tables.action_pay": "Pay",
    "tables.action_clean": "Clean",
    "tables.action_occupy": "Occupy",
    "tables.btn_update_order": "Update Order",
    "tables.btn_new_order": "Start New Order",
    "tables.area_main": "Main Dining",
    "tables.area_patio": "Patio",
    "tables.area_bar": "Bar",
    "tables.area_private": "Private",

    // POS
    "pos.search_placeholder": "Search dishes...",
    "pos.edit_menu": "Edit Menu",
    "pos.editing_mode": "Editing Mode",
    "pos.add_dish": "Add New Dish",
    "pos.out_of_stock": "Out of Stock",
    "pos.limit_reached": "Limit Reached",
    "pos.low_stock": "Low Stock",
    "pos.in_stock": "In Stock",
    "pos.order_details": "Order Details",
    "pos.dine_in": "Dine In",
    "pos.takeaway": "Takeaway",
    "pos.delivery": "Delivery",
    "pos.filter_cart": "Filter cart items...",
    "pos.no_results": "No items match your search",
    "pos.cart_empty": "Cart is empty",
    "pos.subtotal": "Subtotal",
    "pos.discount": "Discount",
    "pos.tax": "Tax",
    "pos.total": "Total",
    "pos.place_order": "Place Order",
    "pos.cat_all": "All Items",
    "pos.cat_pho": "Phở & Noodles",
    "pos.cat_rice": "Rice Dishes",
    "pos.cat_banhmi": "Bánh Mì",
    "pos.cat_beverages": "Beverages",
    "pos.cat_desserts": "Desserts",
    "pos.modal_add": "Add to Order",
    "pos.modal_special": "Special Instructions",
    "pos.modal_stock_avail": "Stock available",

    // Inventory
    "inventory.title": "Inventory",
    "inventory.subtitle": "Manage stock levels and items",
    "inventory.search": "Search inventory...",
    "inventory.sort_name": "Name (A-Z)",
    "inventory.sort_low": "Stock (Low)",
    "inventory.sort_high": "Stock (High)",
    "inventory.filter_all": "All",
    "inventory.filter_low": "Low Stock",
    "inventory.filter_food": "Food",
    "inventory.filter_drink": "Drinks",
    "inventory.filter_ingredient": "Ingredients",
    "inventory.restock": "Restock Needed",
    "inventory.healthy": "Healthy",
    "inventory.no_items": "No items found.",
    "inventory.add_item": "Add Item",
    "inventory.modal_edit": "Edit Item",
    "inventory.modal_new": "New Inventory Item",
    "inventory.basic_info": "Basic Info",
    "inventory.stock_details": "Stock Details",
    "inventory.current": "Current",
    "inventory.min_threshold": "Min Threshold",
    "inventory.unit": "Unit",
    "inventory.description": "Description",
    "inventory.ai_fill": "AI Fill",
    "inventory.thinking": "Thinking...",
    "inventory.update": "Update Item",
    "inventory.save": "Save Item",
    "inventory.delete_title": "Delete Item?",
    "inventory.delete_confirm": "Are you sure you want to remove this item? This cannot be undone.",
    "inventory.cancel": "Cancel",
    "inventory.delete": "Delete",

    // Reports
    "reports.dashboard": "POS Dashboard",
    "reports.title": "Performance Reports",
    "reports.revenue": "Revenue",
    "reports.expenses": "Expenses",
    "reports.ai_insights": "AI Insights",
    "reports.analyzing": "Analyzing...",
    "reports.today": "Today",
    "reports.week": "Last 7 Days",
    "reports.month": "This Month",
    "reports.year": "This Year",
    "reports.gross_revenue": "Gross Revenue",
    "reports.prev": "Prev",
    "reports.total_orders": "Total Orders",
    "reports.analytics": "Revenue Analytics",
    "reports.recent_transactions": "Recent Transactions",
    "reports.estimated_expenses": "Estimated Expenses",
    "reports.net_profit": "Net Profit",
    "reports.margin": "Margin",

    // Checkout
    "checkout.title": "Checkout",
    "checkout.success": "Payment Successful!",
    "checkout.completed": "Order has been completed.",
    "checkout.back_tables": "Back to Tables",
    "checkout.new_order": "New Order",
    "checkout.summary": "Order Summary",
    "checkout.table": "Table",
    "checkout.note": "Note",
    "checkout.payment_method": "Payment Method",
    "checkout.cash": "Cash",
    "checkout.card": "Card",
    "checkout.qr": "QR Code",
    "checkout.wallet": "Wallet",
    "checkout.confirm": "Confirm Payment",
    "checkout.processing": "Processing...",

    // Order History
    "history.title": "Order History",
    "history.subtitle": "View and manage past transactions",
    "history.export": "Export CSV",
    "history.search": "Search by Order ID, Customer Name...",
    "history.all_time": "All Time",
    "history.today": "Today",
    "history.yesterday": "Yesterday",
    "history.last_7_days": "Last 7 Days",
    "history.no_orders": "No orders found matching your criteria",
    "history.items": "items",

    // Admin Dashboard
    "admin.title": "Admin Dashboard",
    "admin.welcome": "Welcome back",
    "admin.launch_pos": "Launch POS System",
    "admin.launch_desc": "Access tables, orders, inventory and reports.",
    "admin.enter_app": "Enter App",
    "admin.create_user": "Create Management Account",
    "admin.create_desc": "Register new Admins or Managers for the system.",
    "admin.create_btn": "Create Account",

    // Admin User Create
    "user_create.back": "Back to Dashboard",
    "user_create.title": "Create Staff Account",
    "user_create.subtitle": "Register new management or admin personnel",
    "user_create.fullname": "Full Name",
    "user_create.email": "Email Address",
    "user_create.password": "Password",
    "user_create.role": "Role Permission",
    "user_create.creating": "Creating...",
    "user_create.create": "Create Account"
  },
  vi: {
    // Nav
    "nav.tables": "Bàn",
    "nav.menu": "Thực đơn",
    "nav.history": "Lịch sử",
    "nav.inventory": "Kho hàng",
    "nav.reports": "Báo cáo",
    "nav.settings": "Cài đặt",
    "nav.logout": "Đăng xuất",

    // Settings
    "settings.title": "Cài đặt",
    "settings.subtitle": "Quản lý tùy chọn và cấu hình hệ thống",
    "settings.general": "Chung",
    "settings.appearance": "Giao diện",
    "settings.appearance_desc": "Tùy chỉnh giao diện hiển thị",
    "settings.light": "Sáng",
    "settings.dark": "Tối",
    "settings.language": "Ngôn ngữ",
    "settings.language_desc": "Chọn ngôn ngữ hiển thị ưu thích",
    "settings.currency": "Tiền tệ",
    "settings.currency_desc": "Đơn vị tiền tệ mặc định",
    "settings.business": "Doanh nghiệp",
    "settings.tax": "Thuế suất (%)",
    "settings.tax_desc": "Áp dụng cho tất cả đơn hàng",
    "settings.save": "Lưu",
    "settings.notifications": "Thông báo",
    "settings.order_alerts": "Thông báo đơn hàng",
    "settings.order_alerts_desc": "Nhận thông báo khi có đơn mới",
    "settings.stock_alerts": "Cảnh báo tồn kho",
    "settings.stock_alerts_desc": "Cảnh báo khi sắp hết hàng",
    "settings.about": "Giới thiệu",
    "settings.edit_profile": "Chỉnh sửa hồ sơ",
    "settings.avatar_url": "Đường dẫn ảnh đại diện",
    "settings.avatar_hint": "Bấm vào ảnh để tải lên",
    "settings.randomize": "Ngẫu nhiên",
    "settings.security": "Bảo mật",
    "settings.change_password": "Đổi mật khẩu",
    "settings.change_password_desc": "Cập nhật mật khẩu tài khoản của bạn",
    "settings.current_password": "Mật khẩu hiện tại",
    "settings.new_password": "Mật khẩu mới",
    "settings.confirm_password": "Xác nhận mật khẩu",
    "settings.password_match_error": "Mật khẩu không khớp",
    "settings.password_old_error": "Mật khẩu hiện tại không đúng",
    "settings.password_updated": "Đã cập nhật mật khẩu thành công",
    "role.admin": "Quản trị",
    "role.manager": "Quản lý",
    "role.cashier": "Thu ngân",

    // Login
    "login.welcome": "Chào mừng trở lại",
    "login.subtitle": "Vui lòng nhập thông tin để đăng nhập.",
    "login.create_account": "Tạo tài khoản",
    "login.create_subtitle": "Tham gia EcoPOS với vai trò thu ngân.",
    "login.email": "Địa chỉ Email",
    "login.password": "Mật khẩu",
    "login.fullname": "Họ và tên",
    "login.signin": "Đăng nhập",
    "login.signup": "Đăng ký",
    "login.already_have_account": "Đã có tài khoản?",
    "login.dont_have_account": "Chưa có tài khoản?",
    "login.brand_subtitle": "Giải pháp thông minh, bền vững cho quản lý nhà hàng hiện đại.",
    "login.feature_floor": "Sơ đồ bàn thời gian thực",
    "login.feature_inventory": "Kho hàng thông minh",
    "login.feature_analytics": "Phân tích AI",

    // Tables
    "tables.title": "Sơ đồ bàn",
    "tables.live_view": "Trực tiếp",
    "tables.editing": "Đang chỉnh sửa...",
    "tables.add_table": "Thêm bàn",
    "tables.edit_layout": "Sửa bố cục",
    "tables.done": "Xong",
    "tables.all_areas": "Tất cả",
    "tables.status_open": "Trống",
    "tables.status_occupied": "Có khách",
    "tables.status_dirty": "Dơ",
    "tables.seats": "Ghế",
    "tables.guests": "Khách",
    "tables.time": "Thời gian",
    "tables.current_order": "Đơn hiện tại",
    "tables.action_order": "Gọi món",
    "tables.action_pay": "Thanh toán",
    "tables.action_clean": "Dọn dẹp",
    "tables.action_occupy": "Xếp chỗ",
    "tables.btn_update_order": "Cập nhật đơn",
    "tables.btn_new_order": "Bắt đầu đơn mới",
    "tables.area_main": "Sảnh chính",
    "tables.area_patio": "Ngoài trời",
    "tables.area_bar": "Quầy bar",
    "tables.area_private": "Phòng riêng",

    // POS
    "pos.search_placeholder": "Tìm món...",
    "pos.edit_menu": "Sửa thực đơn",
    "pos.editing_mode": "Chế độ sửa",
    "pos.add_dish": "Thêm món mới",
    "pos.out_of_stock": "Hết hàng",
    "pos.limit_reached": "Đạt giới hạn",
    "pos.low_stock": "Sắp hết",
    "pos.in_stock": "Còn hàng",
    "pos.order_details": "Chi tiết đơn",
    "pos.dine_in": "Tại bàn",
    "pos.takeaway": "Mang đi",
    "pos.delivery": "Giao hàng",
    "pos.filter_cart": "Lọc giỏ hàng...",
    "pos.no_results": "Không tìm thấy món",
    "pos.cart_empty": "Giỏ hàng trống",
    "pos.subtotal": "Tạm tính",
    "pos.discount": "Giảm giá",
    "pos.tax": "Thuế",
    "pos.total": "Tổng cộng",
    "pos.place_order": "Đặt đơn",
    "pos.cat_all": "Tất cả",
    "pos.cat_pho": "Phở & Bún",
    "pos.cat_rice": "Cơm",
    "pos.cat_banhmi": "Bánh Mì",
    "pos.cat_beverages": "Đồ uống",
    "pos.cat_desserts": "Tráng miệng",
    "pos.modal_add": "Thêm vào đơn",
    "pos.modal_special": "Ghi chú đặc biệt",
    "pos.modal_stock_avail": "Tồn kho khả dụng",

    // Inventory
    "inventory.title": "Kho hàng",
    "inventory.subtitle": "Quản lý mức tồn kho và mặt hàng",
    "inventory.search": "Tìm kiếm kho...",
    "inventory.sort_name": "Tên (A-Z)",
    "inventory.sort_low": "Tồn kho (Thấp)",
    "inventory.sort_high": "Tồn kho (Cao)",
    "inventory.filter_all": "Tất cả",
    "inventory.filter_low": "Sắp hết",
    "inventory.filter_food": "Đồ ăn",
    "inventory.filter_drink": "Đồ uống",
    "inventory.filter_ingredient": "Nguyên liệu",
    "inventory.restock": "Cần nhập hàng",
    "inventory.healthy": "Ổn định",
    "inventory.no_items": "Không tìm thấy hàng.",
    "inventory.add_item": "Thêm hàng",
    "inventory.modal_edit": "Sửa hàng",
    "inventory.modal_new": "Hàng tồn kho mới",
    "inventory.basic_info": "Thông tin cơ bản",
    "inventory.stock_details": "Chi tiết tồn kho",
    "inventory.current": "Hiện tại",
    "inventory.min_threshold": "Mức tối thiểu",
    "inventory.unit": "Đơn vị",
    "inventory.description": "Mô tả",
    "inventory.ai_fill": "Điền AI",
    "inventory.thinking": "Đang nghĩ...",
    "inventory.update": "Cập nhật",
    "inventory.save": "Lưu hàng",
    "inventory.delete_title": "Xóa hàng?",
    "inventory.delete_confirm": "Bạn có chắc chắn muốn xóa mặt hàng này? Hành động này không thể hoàn tác.",
    "inventory.cancel": "Hủy",
    "inventory.delete": "Xóa",

    // Reports
    "reports.dashboard": "Bảng điều khiển POS",
    "reports.title": "Báo cáo hiệu suất",
    "reports.revenue": "Doanh thu",
    "reports.expenses": "Chi phí",
    "reports.ai_insights": "Phân tích AI",
    "reports.analyzing": "Đang phân tích...",
    "reports.today": "Hôm nay",
    "reports.week": "7 ngày qua",
    "reports.month": "Tháng này",
    "reports.year": "Năm nay",
    "reports.gross_revenue": "Tổng doanh thu",
    "reports.prev": "Trước",
    "reports.total_orders": "Tổng đơn",
    "reports.analytics": "Phân tích doanh thu",
    "reports.recent_transactions": "Giao dịch gần đây",
    "reports.estimated_expenses": "Chi phí ước tính",
    "reports.net_profit": "Lợi nhuận ròng",
    "reports.margin": "Biên lợi nhuận",

    // Checkout
    "checkout.title": "Thanh toán",
    "checkout.success": "Thanh toán thành công!",
    "checkout.completed": "Đơn hàng đã hoàn tất.",
    "checkout.back_tables": "Về sơ đồ bàn",
    "checkout.new_order": "Đơn mới",
    "checkout.summary": "Tóm tắt đơn",
    "checkout.table": "Bàn",
    "checkout.note": "Ghi chú",
    "checkout.payment_method": "Phương thức thanh toán",
    "checkout.cash": "Tiền mặt",
    "checkout.card": "Thẻ",
    "checkout.qr": "Mã QR",
    "checkout.wallet": "Ví điện tử",
    "checkout.confirm": "Xác nhận thanh toán",
    "checkout.processing": "Đang xử lý...",

    // Order History
    "history.title": "Lịch sử đơn hàng",
    "history.subtitle": "Xem và quản lý giao dịch cũ",
    "history.export": "Xuất CSV",
    "history.search": "Tìm theo Mã đơn, Tên khách...",
    "history.all_time": "Tất cả",
    "history.today": "Hôm nay",
    "history.yesterday": "Hôm qua",
    "history.last_7_days": "7 ngày qua",
    "history.no_orders": "Không tìm thấy đơn hàng nào",
    "history.items": "món",

    // Admin Dashboard
    "admin.title": "Bảng quản trị",
    "admin.welcome": "Chào mừng trở lại",
    "admin.launch_pos": "Mở hệ thống POS",
    "admin.launch_desc": "Truy cập bàn, đơn hàng, kho và báo cáo.",
    "admin.enter_app": "Vào ứng dụng",
    "admin.create_user": "Tạo tài khoản quản lý",
    "admin.create_desc": "Đăng ký Quản trị viên hoặc Quản lý mới.",
    "admin.create_btn": "Tạo tài khoản",

    // Admin User Create
    "user_create.back": "Quay lại Bảng tin",
    "user_create.title": "Tạo tài khoản nhân viên",
    "user_create.subtitle": "Đăng ký nhân sự quản lý mới",
    "user_create.fullname": "Họ và tên",
    "user_create.email": "Địa chỉ Email",
    "user_create.password": "Mật khẩu",
    "user_create.role": "Quyền hạn",
    "user_create.creating": "Đang tạo...",
    "user_create.create": "Tạo tài khoản"
  },
  fr: {
    // Nav
    "nav.tables": "Tables",
    "nav.menu": "Menu",
    "nav.history": "Historique",
    "nav.inventory": "Inventaire",
    "nav.reports": "Rapports",
    "nav.settings": "Paramètres",
    "nav.logout": "Se déconnecter",

    // Settings
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérer vos préférences et la configuration du système",
    "settings.general": "Général",
    "settings.appearance": "Apparence",
    "settings.appearance_desc": "Personnaliser l'apparence",
    "settings.light": "Clair",
    "settings.dark": "Sombre",
    "settings.language": "Langue",
    "settings.language_desc": "Sélectionnez votre langue préférée",
    "settings.currency": "Devise",
    "settings.currency_desc": "Devise par défaut pour la tarification",
    "settings.business": "Entreprise",
    "settings.tax": "Taux de taxe (%)",
    "settings.tax_desc": "Appliqué à toutes les commandes éligibles",
    "settings.save": "Enregistrer",
    "settings.notifications": "Notifications",
    "settings.order_alerts": "Alertes de commande",
    "settings.order_alerts_desc": "Être notifié d'une nouvelle commande",
    "settings.stock_alerts": "Alerte stock faible",
    "settings.stock_alerts_desc": "Alerte lorsque le stock est bas",
    "settings.about": "À propos",
    "settings.edit_profile": "Modifier le profil",
    "settings.avatar_url": "URL de l'avatar",
    "settings.avatar_hint": "Cliquez sur l'image pour télécharger",
    "settings.randomize": "Aléatoire",
    "settings.security": "Sécurité",
    "settings.change_password": "Changer le mot de passe",
    "settings.change_password_desc": "Mettre à jour le mot de passe de votre compte",
    "settings.current_password": "Mot de passe actuel",
    "settings.new_password": "Nouveau mot de passe",
    "settings.confirm_password": "Confirmer le mot de passe",
    "settings.password_match_error": "Les mots de passe ne correspondent pas",
    "settings.password_old_error": "Mot de passe actuel incorrect",
    "settings.password_updated": "Mot de passe mis à jour avec succès",
    "role.admin": "Admin",
    "role.manager": "Gérant",
    "role.cashier": "Caissier",

    // Login
    "login.welcome": "Bon retour",
    "login.subtitle": "Veuillez entrer vos coordonnées pour vous connecter.",
    "login.create_account": "Créer un compte",
    "login.create_subtitle": "Rejoignez EcoPOS en tant que nouveau caissier.",
    "login.email": "Adresse e-mail",
    "login.password": "Mot de passe",
    "login.fullname": "Nom complet",
    "login.signin": "Se connecter",
    "login.signup": "S'inscrire",
    "login.already_have_account": "Vous avez déjà un compte ?",
    "login.dont_have_account": "Vous n'avez pas de compte ?",
    "login.brand_subtitle": "La solution intelligente et durable pour la gestion moderne de restaurant.",
    "login.feature_floor": "Plan de salle en temps réel",
    "login.feature_inventory": "Inventaire intelligent",
    "login.feature_analytics": "Analytique IA",

    // Tables
    "tables.title": "Plan de salle",
    "tables.live_view": "Vue en direct",
    "tables.editing": "Édition...",
    "tables.add_table": "Ajouter table",
    "tables.edit_layout": "Modifier",
    "tables.done": "Terminé",
    "tables.all_areas": "Toutes zones",
    "tables.status_open": "Libre",
    "tables.status_occupied": "Occupé",
    "tables.status_dirty": "Sale",
    "tables.seats": "Sièges",
    "tables.guests": "Invités",
    "tables.time": "Temps",
    "tables.current_order": "Commande actuelle",
    "tables.action_order": "Commande",
    "tables.action_pay": "Payer",
    "tables.action_clean": "Nettoyer",
    "tables.action_occupy": "Occuper",
    "tables.btn_update_order": "Mettre à jour",
    "tables.btn_new_order": "Nouvelle commande",
    "tables.area_main": "Salle principale",
    "tables.area_patio": "Terrasse",
    "tables.area_bar": "Bar",
    "tables.area_private": "Privé",

    // POS
    "pos.search_placeholder": "Rechercher des plats...",
    "pos.edit_menu": "Modifier menu",
    "pos.editing_mode": "Mode édition",
    "pos.add_dish": "Ajouter plat",
    "pos.out_of_stock": "Rupture de stock",
    "pos.limit_reached": "Limite atteinte",
    "pos.low_stock": "Stock faible",
    "pos.in_stock": "En stock",
    "pos.order_details": "Détails commande",
    "pos.dine_in": "Sur place",
    "pos.takeaway": "Emporter",
    "pos.delivery": "Livraison",
    "pos.filter_cart": "Filtrer panier...",
    "pos.no_results": "Aucun résultat",
    "pos.cart_empty": "Panier vide",
    "pos.subtotal": "Sous-total",
    "pos.discount": "Remise",
    "pos.tax": "Taxe",
    "pos.total": "Total",
    "pos.place_order": "Commander",
    "pos.cat_all": "Tout",
    "pos.cat_pho": "Phở & Nouilles",
    "pos.cat_rice": "Riz",
    "pos.cat_banhmi": "Bánh Mì",
    "pos.cat_beverages": "Boissons",
    "pos.cat_desserts": "Desserts",
    "pos.modal_add": "Ajouter",
    "pos.modal_special": "Instructions spéciales",
    "pos.modal_stock_avail": "Stock disponible",

    // Inventory
    "inventory.title": "Inventaire",
    "inventory.subtitle": "Gérer les niveaux de stock",
    "inventory.search": "Rechercher...",
    "inventory.sort_name": "Nom (A-Z)",
    "inventory.sort_low": "Stock (Bas)",
    "inventory.sort_high": "Stock (Haut)",
    "inventory.filter_all": "Tout",
    "inventory.filter_low": "Stock faible",
    "inventory.filter_food": "Nourriture",
    "inventory.filter_drink": "Boissons",
    "inventory.filter_ingredient": "Ingrédients",
    "inventory.restock": "Réapprovisionner",
    "inventory.healthy": "Sain",
    "inventory.no_items": "Aucun article trouvé.",
    "inventory.add_item": "Ajouter",
    "inventory.modal_edit": "Modifier",
    "inventory.modal_new": "Nouvel article",
    "inventory.basic_info": "Infos de base",
    "inventory.stock_details": "Détails du stock",
    "inventory.current": "Actuel",
    "inventory.min_threshold": "Seuil min",
    "inventory.unit": "Unité",
    "inventory.description": "Description",
    "inventory.ai_fill": "Remplir IA",
    "inventory.thinking": "Réflexion...",
    "inventory.update": "Mettre à jour",
    "inventory.save": "Enregistrer",
    "inventory.delete_title": "Supprimer ?",
    "inventory.delete_confirm": "Êtes-vous sûr de vouloir supprimer cet article ?",
    "inventory.cancel": "Annuler",
    "inventory.delete": "Supprimer",

    // Reports
    "reports.dashboard": "Tableau de bord POS",
    "reports.title": "Rapports de performance",
    "reports.revenue": "Revenus",
    "reports.expenses": "Dépenses",
    "reports.ai_insights": "Analyses IA",
    "reports.analyzing": "Analyse...",
    "reports.today": "Aujourd'hui",
    "reports.week": "7 derniers jours",
    "reports.month": "Ce mois",
    "reports.year": "Cette année",
    "reports.gross_revenue": "Revenu brut",
    "reports.prev": "Préc",
    "reports.total_orders": "Total commandes",
    "reports.analytics": "Analytique des revenus",
    "reports.recent_transactions": "Transactions récentes",
    "reports.estimated_expenses": "Dépenses estimées",
    "reports.net_profit": "Bénéfice net",
    "reports.margin": "Marge",

    // Checkout
    "checkout.title": "Caisse",
    "checkout.success": "Paiement réussi !",
    "checkout.completed": "La commande est terminée.",
    "checkout.back_tables": "Retour aux tables",
    "checkout.new_order": "Nouvelle commande",
    "checkout.summary": "Résumé",
    "checkout.table": "Table",
    "checkout.note": "Note",
    "checkout.payment_method": "Méthode de paiement",
    "checkout.cash": "Espèces",
    "checkout.card": "Carte",
    "checkout.qr": "QR Code",
    "checkout.wallet": "Portefeuille",
    "checkout.confirm": "Confirmer paiement",
    "checkout.processing": "Traitement...",

    // Order History
    "history.title": "Historique",
    "history.subtitle": "Voir les transactions passées",
    "history.export": "Exporter CSV",
    "history.search": "Rechercher par ID, Nom...",
    "history.all_time": "Tout le temps",
    "history.today": "Aujourd'hui",
    "history.yesterday": "Hier",
    "history.last_7_days": "7 derniers jours",
    "history.no_orders": "Aucune commande trouvée",
    "history.items": "articles",

    // Admin Dashboard
    "admin.title": "Tableau de bord Admin",
    "admin.welcome": "Bon retour",
    "admin.launch_pos": "Lancer POS",
    "admin.launch_desc": "Accéder aux tables, commandes, stocks.",
    "admin.enter_app": "Entrer",
    "admin.create_user": "Créer compte de gestion",
    "admin.create_desc": "Inscrire nouveaux Admins ou Gérants.",
    "admin.create_btn": "Créer compte",

    // Admin User Create
    "user_create.back": "Retour",
    "user_create.title": "Créer compte personnel",
    "user_create.subtitle": "Inscrire nouveau personnel",
    "user_create.fullname": "Nom complet",
    "user_create.email": "Adresse e-mail",
    "user_create.password": "Mot de passe",
    "user_create.role": "Rôle",
    "user_create.creating": "Création...",
    "user_create.create": "Créer compte"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('eco_lang') as Language) || 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eco_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};